mysql:
  image: mysql:5.7
  container_name: mysql
  environment:
    MYSQL_DATABASE: 'mysql'
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: '12345678'
    MYSQL_ROOT_PASSWORD: '12345678'
  ports:
    - "3306:3306"
  volumes:
    - ./data/conf.d:/etc/mysql/conf.d
    - ./data/logs:/logs
    - /usr/local/var/mysql:/var/lib/mysql